# Generated by Django 3.0.8 on 2021-08-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cName', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('cEmail', models.EmailField(max_length=254)),
                ('cLogo', models.ImageField(blank=True, upload_to='images')),
                ('cUrl', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sRollno', models.IntegerField()),
                ('sName', models.CharField(max_length=50, unique='true')),
                ('sAddress', models.CharField(max_length=50)),
                ('sEmail', models.EmailField(max_length=254)),
                ('sCourse', models.CharField(max_length=20)),
                ('sFeeStatus', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'StudentDetails',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Name', models.CharField(max_length=50, unique='true')),
                ('Course', models.CharField(max_length=20)),
                ('MaxMarks', models.IntegerField()),
                ('MarksObtained', models.IntegerField()),
                ('Result', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'StudentResult',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eFname', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('eLname', models.CharField(max_length=50)),
                ('eEmail', models.EmailField(max_length=254)),
                ('ePhone', models.CharField(max_length=50)),
                ('eCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.Company')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
