# Generated by Django 3.0.8 on 2021-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sName',
            field=models.CharField(max_length=50, primary_key='true', serialize=False, unique='true'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='Name',
            field=models.CharField(max_length=50, primary_key='true', serialize=False, unique='true'),
        ),
    ]
