# Generated by Django 3.0.8 on 2021-08-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0002_auto_20210826_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='Rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirai.StudentDetails'),
        ),
    ]
