# Generated by Django 3.0.8 on 2021-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0003_auto_20210826_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='Rollno',
            field=models.IntegerField(),
        ),
    ]
